### ISSUE TITLE
Could you add Arome (Antilles, Guyane, Réunion-Mayotte, Polynésie, Nouvelle-Calédonie)?

### ISSUE THREAD

**Issue by sailgrib** [OpenMeteoData/meteo-france-models#10]
Thanks for this awesome service.
Could you add Arome (Antilles, Guyane, Réunion-Mayotte, Polynésie, Nouvelle-Calédonie) which are available as well?
Thanks,

Henri

**Comment by nbald** [comment]
This service will be permanently shut down on December 9, 2024.
