### ISSUE TITLE
MIssing data in arome-france-hd/v1/S2 package

### ISSUE THREAD

**Issue by jakub-valenta** [OpenMeteoData/meteo-france-models#11]
Hi,

recently some forecast rundowns in  [https://mf-models-on-aws.org/#arome-france-hd/v1/](https://mf-models-on-aws.org/#arome-france-hd/v1/) contain incomplete S2 package (files for first few hours are missing):

[2022-06-18/00/SP2 (missing 01 - 10H)](https://mf-models-on-aws.org/#arome-france-hd/v1/2022-06-18/00/SP2/)
[2022-06-18/06/SP2 (missing 01 - 03H)](https://mf-models-on-aws.org/#arome-france-hd/v1/2022-06-18/06/SP2/)
[2022-06-18/12/SP2 (missing 01 - 02H)](https://mf-models-on-aws.org/#arome-france-hd/v1/2022-06-18/12/SP2/)
[2022-06-19/00/SP2 (missing 01 - 06H)](https://mf-models-on-aws.org/#arome-france-hd/v1/2022-06-19/00/SP2/)
[2022-06-19/06/SP2 (missing 01 - 08H)](https://mf-models-on-aws.org/#arome-france-hd/v1/2022-06-19/06/SP2/)
[2022-06-20/06/SP2 (missing 01 - 05H)](https://mf-models-on-aws.org/#arome-france-hd/v1/2022-06-20/06/SP2/)

It looks this happens randomly and S1 package is always complete. Could you please look into it?

Best Regards

**Comment by vtoupet** [comment]
It happens randomly but more and more often. Does anyone know the reason? Are the missing files present on the météo France servers?

**Comment by jakub-valenta** [comment]
I have checked missing data from 2022-08-04 06:00:00 and those files are missing on Meteo France servers too.

**Comment by jakub-valenta** [comment]
I have checked data from 2022-08-04 06:00:00 and it looks like they are present on meteo france servers.

**Comment by kevinrosa** [comment]
This happened again on 2022-08-09 for the arome-france-hd/v1/S2 package.

**Comment by kevinrosa** [comment]
@nbald is it possible to contribute to the back-end code?

**Comment by vtoupet** [comment]
> @nbald is it possible to contribute to the back-end code?

@nbald I would be happy to contribute as well

**Comment by nbald** [comment]
The issue comes from the files served by Meteo-France being corrupted.
That is why they cannot pass our integrity tests.

`$ curl -s "http://dcpc-nwp.meteo.fr/services/PS_GetCache_DCPCPreviNum?&token=__5yLVTdr-sGeHoPitnFc7TZ6MhBcJxuSsoZp6y0leVHU__&model=AROME&grid=0.01&package=SP2&time=02H&referencetime=2022-08-24T00:00:00Z&format=grib2" | wgrib2 -`

Wgrib2 output :

```
1:0:d=2022082400:RPRATE:surface:0-2 hour acc fcst:

*** FATAL ERROR: inconsistent number of bitmap points sec3-sec5: 0 sec6: 856076 ***

2:1308140:d=2022082400:SPRATE:surface:0-2 hour acc fcst:
```

Expected output should be similar to this :
```
1:0:d=2022082400:RPRATE:surface:0-2 hour acc fcst:
2:2987654:d=2022082400:SPRATE:surface:0-2 hour acc fcst:
3:3636100:d=2022082400:GPRATE:surface:0-2 hour acc fcst:
4:4347187:d=2022082400:PRES:surface:2 hour fcst:
5:8955860:d=2022082400:LCDC:surface:2 hour fcst:
6:11220495:d=2022082400:HCDC:surface:2 hour fcst:
7:12582528:d=2022082400:MCDC:surface:2 hour fcst:
8:14178311:d=2022082400:CAPE:surface - 3000 m above ground:2 hour fcst:
9:18806292:d=2022082400:var discipline=0 center=85 local_table=0 parmcat=16 parm=193:surface:2 hour fcst:
```

**Comment by nbald** [comment]
I have deployed a quick fix to re-encode the grib file when the problem occurs.
I have not done extensive testing, but it seems to work. Let me know if something is wrong.

Example of a regular file :
https://mf-nwp-models.s3.amazonaws.com/arome-france-hd/v1/2022-08-23/00/SP2/10H.grib2

Example of corrupted-then-reencoded file:
https://mf-nwp-models.s3.amazonaws.com/arome-france-hd/v1/2022-08-24/00/SP2/10H.grib2

**Comment by nbald** [comment]
The incident is closed
