### ISSUE TITLE
Missing Arpege-Europe 12Z Files

### ISSUE THREAD

**Issue by karldevinenetweather** [OpenMeteoData/meteo-france-models#15]
Hi,
It seems that every day a selection of 12Z files for Arpege-Europe are missing from the AWS server.

Example: 
https://mf-models-on-aws.org/#arpege-europe/v1/2023-10-03/12/SP1/  - has just 00H12H and 85H96H available. 
There are missing files on this run every single day.

**Comment by vtoupet** [comment]
@nbald What can we do to speed up resolution ? Thanks

**Comment by nbald** [comment]
Hi
I just fixed it.
It should work now.

**Comment by karldevinenetweather** [comment]
much better thankyou

**Comment by nbald** [comment]
This service will be permanently shut down on December 9, 2024.
