### ISSUE TITLE
103H114H files missing from 12h models

### ISSUE THREAD

**Issue by atelierdesdonnees** [OpenMeteoData/meteo-france-models#17]
Hi,
it seems that the 103H114H files are missing from the noon generation. I have not browsed all days but some, and I have found the same every time.
Is it something you could repair?
Thanks!

**Comment by nbald** [comment]
It's not a bug. Météo-France no longer distributes data beyond 102 hours.

**Comment by atelierdesdonnees** [comment]
Oh, my mistake then... They haven't updated their doc.
Thanks for the tip!

**Comment by nbald** [comment]
This service will be permanently shut down on December 9, 2024.
