### ISSUE TITLE
only 1 month history ?

### ISSUE THREAD

**Issue by waminos** [OpenMeteoData/meteo-france-models#19]
Hi, 
I tried to query data earlier than a month but it seems not working. 
`https://mf-nwp-models.s3.amazonaws.com/arome-france-hd/v1/2024-07-04/00/SP1/00H.grib2`
We don't we have access to more historical data ? 
Thanks a lot 
@nbald

**Comment by nbald** [comment]
https://github.com/OpenMeteoData/meteo-france-models/issues/20

**Comment by nbald** [comment]
This service will be permanently shut down on December 9, 2024.
