### ISSUE TITLE
AROME model 2019-06-25 file is broken

### ISSUE THREAD

**Issue by etoodu** [OpenMeteoData/meteo-france-models#2]
AROME 2019-06-25 run 12 SP1 hour 26H file is broken. 
aws s3 location: s3://mf-nwp-models/arome-france-hd/v1/2019-06-25/12/SP1/26H.grib2
File is only 6.2 M and contains one variable, rest of the messages are unreadable.

**Comment by nbald** [comment]
Hello
I have investigated, and it seems that is was an isolated event. We will still make the appropriate modification to make our process even more reliable
