### ISSUE TITLE
Missing ARPEGE-EUROPE files

### ISSUE THREAD

**Issue by nbald** [OpenMeteoData/meteo-france-models#3]
00-12h forecast time-steps are missing for some ARPEGE-EUROPE surface parameters.
It started on July 1, 12z.

We are currently investigating the issue

**Comment by nbald** [comment]
Meteo-France have modified the content of the SP1 file without notifying anyone in advance. I am quite pissed-of. This is very unprofessional.

The 10m GUST, UGUST, VGUST are no longer available for time-step 00 in the files provided by Meteo-France.

So the files did not pass our corruption tests. We fixed our tests, but those three variables remains unavailable.

We have notified Meteo-France about this issue.

**Comment by nbald** [comment]
More files have been modified by Meteo-France today. It now affect surface parameters for all the models (SP1 and SP2 files)
We are updating our systems to take account of these changes.

**Comment by nbald** [comment]
Here is the (final?) list of the changes:

- CDCON disappear from AROME-FRANCE (SP2)

- GUST, UGUST and VGUST at timestep 0 disappear from AROME-FRANCE and ARPEGE-WORLD (SP1)

- T2 min-max average periods are altered in ARPEGE EUROPE (SP2) :
54-60 -> 57-60
60-66 -> 63-66
66-72 -> 69-72
72-78 -> 75-78
84-90->78-90
90-96 -> 78-96
96-102 -> 78-102

- T2 min-max average periods are altered in ARPEGE WORLD (SP2):
54-60 -> 57-60
60-66 -> 63-66
66-72 -> 69-72
72-78 -> 75-78
84-87 -> 78-87
84-90 -> 78-90
90-93 -> 78-93
90-96 -> 78-96
90-102 -> 78->102 

Our systems have been updated. Everything should be back to normal starting 12z run.
(unless MF decide to make other unexpected changes...)

**Comment by nbald** [comment]
Official message from Meteo-France :

> Notre référence : T#26968
> 
> Bonjour chers utilisateurs de données publiques
> 
>  
> 
> Météo France a réalisé une évolution importante de sa chaine de Prévision Numérique du Temps le 2 juillet. Notre objectif était une totale transparence pour les utilisateurs.
> 
> Toutefois et malgré les précautions prises, nous observons quelques impacts dans le contenu des packages de modèle ainsi que dans l'accès par WS INSPIRE. Nous nous excusons pour la gène occasionnée.
> 
>  
> 
> S'agissant de l'accès aux modèles par WS INSPIRE, la grille ARPEGE sur le GLOBE en résolution 0.5° n'est  plus disponible. Elle sera remplacée dans les plus bref délais par la nouvelle grille ARPEGE en résolution 0.25°. Une liste de diffusion pour informer l'ensemble des usagers de ces données est créée, pour vous y inscrire, merci de nous écrire à l'adresse mail suivante : support.inspire@meteo.fr.
> 
>  
> 
> Météo France renouvèle ses excuses pour les impacts que ces changements involontaires pourraient avoir sur vos applications.
>  
> Bonne réception et bonne journée,
>  
> Cordialement,
> Cédric Legal

**Comment by jpmacveigh** [comment]
Bravo Nicolas pour tout ce travail. J'espère que MF ne va pas encore changer ses processus sans avertir ses usagers.
