### ISSUE TITLE
Wrong names for inventory files

### ISSUE THREAD

**Issue by fox91** [OpenMeteoData/meteo-france-models#4]
In the documentation there is this (wrong) statement:
_To get the inventory file, replace `.grib2` extension with `.inv` in the url._

In practice it is indicated that these are the names of the files:
 - [`example.grib2`](https://mf-nwp-models.s3.amazonaws.com/arome-france-hd/v1/2019-06-16/00/HP1/00H.grib2)
 - [`example.inv`](https://mf-nwp-models.s3.amazonaws.com/arome-france-hd/v1/2019-06-16/00/HP1/00H.inv) _(404 Not Found)_

In reality, these are the names found on S3:
 - [`example.grib2`](https://mf-nwp-models.s3.amazonaws.com/arome-france-hd/v1/2019-06-16/00/HP1/00H.grib2)
 - [`example.grib2.inv`](https://mf-nwp-models.s3.amazonaws.com/arome-france-hd/v1/2019-06-16/00/HP1/00H.grib2.inv)

Personally I find the solution documented more correct and clean, the problem is that it does not correspond to reality, so either the files are adapted to the documentation or the documentation is adapted to the files.

I found the same error for all models, for new and old runs, for both versions.

**Comment by nbald** [comment]
Hello.

Yes, this is an error. I will fix the documentation ASAP.

**Comment by nbald** [comment]
This service will be permanently shut down on December 9, 2024.
