### ISSUE TITLE
IMPORTANT CHANGES

### ISSUE THREAD

**Issue by nbald** [OpenMeteoData/meteo-france-models#8]
Meteo-France will make some changes to the files they serve, starting January 12th of 2022.

The content of the files remains the same, but the parameterNumber, discipline and category might be different.

It will be necessary to update your processes. See https://donneespubliques.meteofrance.fr/

In addition, as a result of this change, the v2 files will be unavailable from January 12th to beginning of February..
The v1 files will remain available - as exact copies of the files served by Meteo-France.

**Comment by meteoDaniel** [comment]
Dear @nbald after you have adapted the changes from v1 to v2., do you provide data back to 12th January again or just ongoing?


Thanks a lot
Daniel

**Comment by meteoDaniel** [comment]
@nbald can we help you to bring back the service online? 
Best regards

**Comment by meteomara** [comment]
Would be interesting to know if the V2 files will be coming back at all.

**Comment by koeleboe** [comment]
@nbald Do you have any update on this? Will the V2 files be back online or not? The site says the beginning of February :)

**Comment by nbald** [comment]
V2 files won't get back online. We will stick to serving raw data from meteo-france
