### ISSUE TITLE
TWATP parameter in Arome model

### ISSUE THREAD

**Issue by blaza1** [OpenMeteoData/meteo-france-models#9]
Hi,

Thanks for this great site. We have found it very useful.

We extract various paramters from the AROME mode using xarray and pyniol After the change on the 26th of Janaury I have been able to find 5 or 6 parameters where the name has changed. However I can't find what the new name of the TWATP paramteter is. It's long name is Total water precipitation and the unit is kg m-2

- What has this parameter changed to or can I derive this paramter from another one ?

- Is there any processing which happens between meteofrance and OpenMeteoData ? I noticed meteofrance provides only raw data without a .env file.

- Is there any documentation for the Arome model ? I have found the meteofrance info difficult to use and out of date. It;s a shame as the model itself is great.

Thanks for any help.

**Comment by nbald** [comment]
This service will be permanently shut down on December 9, 2024.
